require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - '*.gemspec'
    - 'Gemfile*'
    - 'bin/**/*'
    - 'test/**/*'
    - 'lib/tasks/*'
    - 'vendor/**/*'

Documentation:
  Enabled: false

Metrics:
  Enabled: false

Style:
  Enabled: false

Layout:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Naming:
  Enabled: false
